const { chromium } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
  const {url} = JSON.parse(fs.readFileSync(path.join(process.env.LOCALAPPDATA, 'ClinicReporterAcceptance/case-queue-v1/current.json')));
  const browser = await chromium.launch({channel:'msedge',headless:true});
  try {
    const page = await browser.newPage({viewport:{width:1080,height:900}});
    const errors=[]; page.on('pageerror',e=>errors.push(e.message));
    await page.goto(url+'app?profile=reporting');
    await page.getByLabel('操作身分',{exact:true}).fill('SYN-REPORTER');
    await page.getByRole('button',{name:'連線',exact:true}).click();
    await page.getByRole('heading',{name:'回報管理清單',exact:true}).waitFor();
    await page.getByText('符合條件 4 案 · 跨日未完成 1 案（優先顯示）',{exact:true}).waitFor();
    await page.getByLabel('選取 SYN-ORDER-1',{exact:true}).check();
    await page.getByLabel('選取 SYN-ORDER-2',{exact:true}).check();
    await page.getByLabel('批次批號',{exact:true}).fill('SYN-SHARED');
    await page.getByLabel('我已核對已選案件，確認取代其全部批號分攤',{exact:true}).check();
    await page.getByRole('button',{name:'套用批次批號',exact:true}).click();
    await page.getByText('批次批號已儲存，清單已更新。',{exact:true}).waitFor();
    async function open(order) {
      await page.getByRole('row').filter({hasText:order}).getByRole('button',{name:'核對此案',exact:true}).click();
      await page.getByLabel('實發數量',{exact:true}).waitFor();
    }
    await open('SYN-ORDER-1');
    assert.equal(await page.getByLabel('批號 1',{exact:true}).inputValue(),'SYN-SHARED');
    await page.getByLabel('批號 1',{exact:true}).fill('SYN-LOT-A');
    await page.getByLabel('分攤數量 1',{exact:true}).fill('6');
    await page.getByRole('button',{name:'新增批號分攤',exact:true}).click();
    await page.getByLabel('批號 2',{exact:true}).fill('SYN-LOT-B');
    await page.getByLabel('分攤數量 2',{exact:true}).fill('3');
    await page.getByRole('button',{name:'儲存發藥核對',exact:true}).click();
    await page.getByRole('alert').filter({hasText:'分攤合計相符'}).waitFor();
    await page.getByLabel('分攤數量 2',{exact:true}).fill('4');
    await page.getByRole('button',{name:'儲存發藥核對',exact:true}).click();
    await page.getByText('回報核對已儲存，清單已更新。',{exact:true}).waitFor();
    await open('SYN-ORDER-2');
    assert.equal(await page.getByLabel('批號 1',{exact:true}).inputValue(),'SYN-SHARED');
    await open('SYN-ORDER-1');
    await page.getByLabel('實發數量',{exact:true}).fill('5');
    await page.getByRole('button',{name:'移除批號 2',exact:true}).click();
    await page.getByLabel('分攤數量 1',{exact:true}).fill('5');
    await page.getByRole('button',{name:'儲存發藥核對',exact:true}).click();
    assert.equal(await page.getByLabel('數量修改原因',{exact:true}).evaluate(el=>el.validity.valueMissing),true);
    await page.getByLabel('數量修改原因',{exact:true}).fill('合成少發 5 顆');
    await page.getByRole('button',{name:'儲存發藥核對',exact:true}).click();
    await page.getByText('回報核對已儲存，清單已更新。',{exact:true}).waitFor();
    await open('SYN-ORDER-1');
    await page.getByText('來源量 10 顆；回報量 5 顆',{exact:true}).waitFor();
    await page.getByLabel('排除或納入原因',{exact:true}).fill('合成未領藥');
    await page.getByRole('button',{name:'確認排除此案',exact:true}).click();
    await page.getByText('回報核對已儲存，清單已更新。',{exact:true}).waitFor();
    assert.equal(await page.getByRole('row').filter({hasText:'SYN-ORDER-1'}).count(),0);
    await page.getByLabel('狀態篩選',{exact:true}).selectOption('excluded');
    await page.getByRole('button',{name:'查詢清單',exact:true}).click();
    await page.getByText('符合條件 1 案 · 跨日未完成 0 案（優先顯示）',{exact:true}).waitFor();
    await page.getByRole('row').filter({hasText:'SYN-ORDER-1'}).getByRole('button',{name:'核對此案',exact:true}).click();
    await page.getByRole('button',{name:'確認重新納入',exact:true}).waitFor();
    assert.equal(await page.getByLabel('實發數量',{exact:true}).count(),0);
    await page.getByLabel('排除或納入原因',{exact:true}).fill('合成確認已領藥');
    await page.getByRole('button',{name:'確認重新納入',exact:true}).click();
    await page.getByText('回報核對已儲存，清單已更新。',{exact:true}).waitFor();
    await page.getByLabel('狀態篩選',{exact:true}).selectOption('active');
    await page.getByLabel('異常篩選',{exact:true}).selectOption('quantity_changed');
    await page.getByRole('button',{name:'查詢清單',exact:true}).click();
    await page.getByText('符合條件 1 案 · 跨日未完成 0 案（優先顯示）',{exact:true}).waitFor();
    await open('SYN-ORDER-1');
    assert.equal(await page.getByLabel('實發數量',{exact:true}).inputValue(),'5');
    await page.getByText('案件稽核歷史',{exact:true}).click();
    await page.getByText('原因：合成未領藥',{exact:true}).waitFor();
    await page.getByText('原因：合成確認已領藥',{exact:true}).waitFor();
    await page.getByText('原因：合成少發 5 顆',{exact:true}).waitFor();
    await page.setViewportSize({width:720,height:900});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    fs.mkdirSync(path.join(__dirname,'../../screenshots'),{recursive:true});
    await page.screenshot({path:path.join(__dirname,'../../screenshots/reporting-720.png'),fullPage:true});
    await page.getByLabel('實發數量',{exact:true}).fill('4');
    await page.evaluate(()=>window.dispatchEvent(new Event('offline')));
    await page.getByRole('button',{name:'連線',exact:true}).waitFor();
    assert.equal(await page.getByLabel('實發數量',{exact:true}).count(),0);
    assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);
    assert.deepEqual(errors,[]);
    console.log('PASS: reporting bulk/independent lots, 6+3 rejection/6+4 acceptance, audited 10-to-5, exclude/reinclude/history/filter, responsive layout and outage clearing.');
  } finally { await browser.close(); }
})().catch(e=>{console.error(e.message);process.exitCode=1});
